export * from './lib/parser'
export * from './lib/stringify'
export * from './lib/svg'
export * from './lib/types'
export { isGradientColor } from './lib/util'
export { GRADIENT_RE } from './lib/util'
